language: java
jdk:
  - openjdk11

branches:
  only:
    - main

# 현재 위치에서 프로젝트 빌드를 진행할 곳으로 이동
before_script:
  - cd springboot-webservice/

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - yskkjdh@gmail.com